# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-patchos"
BBFILE_PATTERN_meta-patchos = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-patchos = "6"

LAYERDEPENDS_meta-patchos = "core"
LAYERSERIES_COMPAT_meta-patchos = "wrynose"
