DISTRO_NAME = "PatchOS"
DISTRO_VERSION = "0.0.1"
DISTRO_CODENAME = "bootstrap"

MAINTAINER = "Patchset Company"

INIT_MANAGER = "systemd"
PACKAGE_CLASSES = "package_rpm"

DISTRO_FEATURES_OPTED_OUT = " \
    x11 \
    wayland \
"
